import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react';
import axios from 'axios'

export default function Home() {

  const [location, setLocation] = useState("");
  const [data, setData] = useState({});
  const [weather, setWeather] = useState();
  const [errorMessage, setErrorMessage] = useState("");

  let apiKey = process.env.NEXT_PUBLIC_apiKey
  let lang = "en";
  let units = "metric";
  const url = `https://api.openweathermap.org/data/2.5/weather?q=${location}&units=${units}&appid=${apiKey}&lang=${lang}`;
  console.log(url);

  const searchLocation = (event) => {
    if(event.key === "Enter") {
      axios.get(url)
      .then((response)=>{
        console.clear();
        setData(response.data);
        console.log(response.data);
        setWeather(response.data.weather);
        setErrorMessage("");
      }).catch(err=>{
        console.log(err);
        setErrorMessage("Please enter another location");
        setData({});
        setWeather();
      })
      setLocation('');
    }
  }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Weather app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Weather App</h1>
        {errorMessage}
        <h2>Location: {data.name}</h2>
        <input
          value={location}
          onChange={e => setLocation(e.target.value)}
          placeholder="Enter a location..."
          onKeyDown={searchLocation}
          type="text"
        />
        <div>
          {
            weather && weather.map((w, index) => {
              return(
                <div key={index} className={styles.card}>
                  <h3>Current Weather</h3>
                  <h4>Weather type:</h4>
                  <div>{w.main} {data.weather.icon}</div>
                  <h4>Weather description:</h4>
                  <div>{w.description}</div>
                  <h4>Temperature in celsius:</h4>
                  <div>{data.main.temp}</div>
                  <h4>Feels like:</h4>
                  <div>{data.main.feels_like}</div>
                  <h4>Wind:</h4>
                  <div>{data.wind.gust}</div>
                </div>
              )
            })
          }
        </div>
      </main>
    </div>
  )
}
